@host=https://localhost:7164

### Create a new platform (POST)
POST {{host}}/api/platforms
Content-Type: application/json

{
	"name": "Chrome"
}

### Get a platform by ID (GET)
GET {{host}}/api/platforms/10010

### Get all platforms (GET)
GET {{host}}/api/platforms

### Get returned platform (GET)
GET {{host}}/api/Platforms/platform:8a60c208-edf3-4f5d-baf1-081e94a0c6d8